// const { Person } = require("./person");
const dotenv = require("dotenv");
const connectionDb = require("./src/database/connect");
dotenv.config();
connectionDb();
// require("./modules/path");
// require("./modules/fs");
// require("./modules/http");
require("./modules/express");
// const person = new Person("Ednei");
